parameters:
  stage_name: ""
  script_path: ""

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    jobs:
      - job: installation_script_check
        steps:
          - script: |
              ls
              chmod 777 ${{parameters.script_path}}
              ${{parameters.script_path}} ../scripts
              instScript=$(${{parameters.script_path}} ../scripts  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=instScript;isOutput=true]$instScript"
              echo "Release has Installation Script changes: $instScript"
            name: scripts
