parameters:
  stage_name: ""
  template_repo: ""
  script_path: ""

# Description:

# Purpose:

# Expected output:
stages:
  - stage: ${{parameters.stage_name}}
    dependsOn: []
    jobs:
      - job: installation_script_check
        steps:
          - checkout: self
          - checkout: ${{parameters.template_repo}}

          - script: |
              ls
              chmod 777 ${{parameters.template_repo}}/templates/scripts/install_scripts.sh
              ${{parameters.template_repo}}/templates/scripts/install_scripts.sh ${{parameters.script_path}}
              instScript=$(${{parameters.template_repo}}/templates/scripts/install_scripts.sh ${{parameters.script_path}}  | grep "instScript" | cut -d'=' -f 2)
              echo "##vso[task.setVariable variable=instScript;isOutput=true]$instScript"
              echo "Release has Installation Script changes: $instScript"
            name: scripts
